# Generated by Django 2.2 on 2019-05-28 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_curso_codigo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Usuario'),
        ),
        migrations.AddField(
            model_name='problema',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problema',
            name='dificultad',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='problema',
            name='estado',
            field=models.CharField(default='NUEVO', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problema',
            name='funcion',
            field=models.CharField(default='funcion', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problema',
            name='retorno',
            field=models.CharField(default='str', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problema',
            name='tiempo',
            field=models.IntegerField(default=5),
        ),
    ]
