# Generated by Django 2.2 on 2019-05-31 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190530_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopregunta',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentariopregunta',
            name='titulo',
            field=models.CharField(default='Resumen pregunta', max_length=100),
        ),
        migrations.AddField(
            model_name='comentarioproblema',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentarioproblema',
            name='titulo',
            field=models.CharField(default='Resumen pregunta', max_length=100),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(default='Aclaracion', max_length=40),
        ),
    ]
