# Generated by Django 2.2 on 2019-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190602_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tags',
        ),
        migrations.AddField(
            model_name='problema',
            name='tags',
            field=models.ManyToManyField(to='dashboard.Tag'),
        ),
    ]
