# Generated by Django 2.2 on 2019-06-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190602_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='input', max_length=50)),
                ('tipo', models.CharField(default='str', max_length=30)),
                ('descripcion', models.CharField(default='descripcion de input', max_length=300)),
                ('problema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Problema')),
            ],
        ),
    ]
