# Generated by Django 2.2 on 2019-06-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_argumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='resultado_problema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Problema'),
        ),
        migrations.CreateModel(
            name='ResultadoProblema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.BooleanField(default=False)),
                ('ultimo_intento', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Estudiante')),
                ('problema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Problema')),
                ('prueba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Prueba')),
            ],
        ),
    ]
