# Generated by Django 2.2 on 2019-06-02 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190602_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='resultado_problema',
        ),
        migrations.RemoveField(
            model_name='resultadoestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='resultadoestudiante',
            name='problema',
        ),
        migrations.AddField(
            model_name='envio',
            name='problema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Problema'),
        ),
        migrations.DeleteModel(
            name='ResultadoProblema',
        ),
    ]
