# Generated by Django 2.2 on 2019-06-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190602_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='resultado_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ResultadoEstudiante'),
        ),
    ]
