# Generated by Django 2.2 on 2019-06-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_resultadoestudiante_ultimo_intento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='puntaje',
            new_name='avance',
        ),
        migrations.AlterField(
            model_name='envio',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
