# Generated by Django 2.2 on 2019-06-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190602_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='avance',
            field=models.FloatField(default=1),
        ),
    ]
