# Generated by Django 2.2 on 2019-06-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190602_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoestudiante',
            old_name='timestamp',
            new_name='primer_intento',
        ),
    ]
