# Generated by Django 2.2 on 2019-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190602_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problema',
            old_name='retorno',
            new_name='retorno_tipo',
        ),
        migrations.AddField(
            model_name='problema',
            name='retorno_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
