# Generated by Django 2.2 on 2019-06-08 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20190607_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ME', 'Mensaje'), ('RE', 'Nuevo'), ('ER', 'Incorrecto'), ('TD', 'Correcto'), ('WD', 'Trabajo en clase disponible'), ('PE', 'Pregunta estudiante'), ('LO', 'Logro alcanzado')], default='ME', max_length=2)),
                ('contenido', models.CharField(default='Nuevo mensaje', max_length=100)),
                ('leida', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Usuario')),
            ],
        ),
    ]
