# Generated by Django 2.2 on 2019-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20190609_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='medalla',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
