# Generated by Django 2.2 on 2019-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20190610_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumento',
            name='posicion',
            field=models.IntegerField(default=1),
        ),
    ]
