# Generated by Django 2.2 on 2019-06-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20190610_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='problema',
        ),
    ]
