# Generated by Django 2.2 on 2019-06-11 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20190610_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaIO',
            fields=[
                ('prueba_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.Prueba')),
                ('entrada', models.TextField(default='')),
                ('salida', models.TextField(default='')),
            ],
            bases=('dashboard.prueba',),
        ),
        migrations.CreateModel(
            name='PruebaScript',
            fields=[
                ('prueba_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.Prueba')),
                ('script', models.TextField(default='')),
            ],
            bases=('dashboard.prueba',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='worker', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(default='worker', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='resultadoprueba',
            old_name='resultado',
            new_name='resultado_exitoso',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='seccion',
        ),
        migrations.AddField(
            model_name='monitor',
            name='secciones',
            field=models.ManyToManyField(blank=True, to='dashboard.Seccion'),
        ),
        migrations.AddField(
            model_name='problema',
            name='publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='secciones',
            field=models.ManyToManyField(blank=True, to='dashboard.Seccion'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='tipo',
            field=models.CharField(choices=[('OK', 'Script'), ('IO', 'Entrada/Salida')], default='IO', max_length=2),
        ),
        migrations.AlterField(
            model_name='argumento',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=300),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_rev', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_rev', models.DateTimeField()),
                ('estado_revision', models.IntegerField(default=0)),
                ('worker', models.CharField(default='worker', max_length=30)),
                ('envio_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Envio')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='revision_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Revision'),
        ),
    ]
