# Generated by Django 2.2 on 2019-06-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20190611_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('fecha_limite', models.DateTimeField(auto_now_add=True)),
                ('problemas', models.ManyToManyField(to='dashboard.Problema')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Seccion')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.FloatField(default=1)),
                ('puntos', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Estudiante')),
            ],
        ),
    ]
