# Generated by Django 2.2 on 2019-06-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20190612_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='revision_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Revision'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ME', 'Mensaje recibido'), ('RE', 'Nueva respuesta a pregunta'), ('ER', 'Envío revisado'), ('TD', 'Nueva tarea Disponible'), ('TT', 'Se completaron todos los problemas de una tarea'), ('WD', 'Trabajo en clase disponible'), ('PE', 'Un estudiante de su sección dejó una pregunta'), ('LO', 'Medalla otorgada')], default='ME', max_length=2),
        ),
        migrations.AlterField(
            model_name='problema',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
