# Generated by Django 2.2 on 2019-06-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20190612_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='slug',
            field=models.SlugField(),
        ),
    ]
