# Generated by Django 2.2 on 2019-06-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20190612_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoestudiante',
            name='ultimo_envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Envio'),
        ),
    ]
