# Generated by Django 2.2 on 2019-06-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_resultadoestudiante_ultimo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoestudiante',
            name='ultimo_intento',
            field=models.DateTimeField(null=True),
        ),
    ]
