# Generated by Django 2.2 on 2019-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_notificacion_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
