# Generated by Django 2.2 on 2019-06-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20190615_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='preguntas_sin_respuesta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pulso_actividad',
            field=models.FileField(blank=True, null=True, upload_to='pulso/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pulso_puntos',
            field=models.FileField(blank=True, null=True, upload_to='pulso/'),
        ),
    ]
