# Generated by Django 2.2 on 2019-06-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20190616_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
