# Generated by Django 2.2 on 2019-06-22 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_problema_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
