# Generated by Django 2.2 on 2019-06-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_problema_ultima_modificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problema',
            name='numero',
        ),
    ]
