# Generated by Django 2.1.5 on 2019-07-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_prueba_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ME', 'Mensaje recibido'), ('RE', 'Nueva respuesta a pregunta'), ('EE', 'Un nuevo envío fue recibido'), ('ER', 'Envío revisado'), ('TD', 'Nueva tarea Disponible'), ('TT', 'Se completaron todos los problemas de una tarea'), ('WD', 'Trabajo en clase disponible'), ('PE', 'Un estudiante de su sección dejó una pregunta'), ('PP', 'Hay una nueva pregunta para uno de sus problemas'), ('LO', 'Medalla otorgada')], default='ME', max_length=2),
        ),
        migrations.AlterField(
            model_name='revision',
            name='fecha_fin_rev',
            field=models.DateTimeField(null=True),
        ),
    ]
