# Generated by Django 2.2.4 on 2019-08-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20190731_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoprueba',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
