# Generated by Django 2.2.4 on 2019-08-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20190811_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_local',
            field=models.BooleanField(default=False),
        ),
    ]
