# Generated by Django 2.2.4 on 2019-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_usuario_usuario_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='solucion_referencia',
            field=models.TextField(blank=True),
        ),
    ]
