# Generated by Django 2.2.4 on 2019-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_auto_20190908_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='preguntas_sin_respuesta',
        ),
        migrations.AlterField(
            model_name='problema',
            name='nivel_reto',
            field=models.CharField(choices=[('N', 'Ninguno'), ('B', 'Básico'), ('M', 'Intermedio'), ('A', 'Avanzado')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='alias',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
