# Generated by Django 2.2.4 on 2019-09-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20190909_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, default='Tarea', max_length=100, null=True),
        ),
    ]
