# Generated by Django 2.2.4 on 2019-09-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_tarea_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadotarea',
            name='calificacion_tarea',
            field=models.FloatField(default=0),
        ),
    ]
